### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by gabrieldansereau** [gabrieldansereau/betadiversity-hotspots#4]
# ROADMAP

## April 29th
- [ ] PCA of species composition: higher LCBD sites in periphery, should see distinct species assemblages (or dbRDA)
- [ ] Variation by years, month, or season
  - 5 year segments, bi-annual divisions, etc.
  - TBI or other species gains vs losses measures
  - BC plots comparing biogeographic regions
- [ ] dbRDA to investigate vertical delimitation in the Prairies
- [ ] IUCN distribution maps to limit farther predictions
- [ ] Kriging & visualization of prediction error
- [x] LCBD on moving windows
- [x] Embarcadero
  - [x] Prediction for NE zone
  - [ ] Map uncertainty
  - [ ] Variable importance + spatial/temporal importance

## April 13th
- [x] Extract 2 areas of interest
  - [x] Calculate LCBDs separately
  - [x] Histogram2D for LCBD-richness relationship
- [x] Randoms Forests on species richness
- [ ] Start article draft
- [ ] Supp.mat
  - [ ] Variable importance: 60sp x 30 vars matrix
  - [ ] Model evaluation: Scatter plot of ordered AUC values

## Previous
- [ ] Clarify eBird data extraction (#11)
- [ ] First article outline
- [ ] Moving window on LCBD values
- [ ] Use LabelledArrays.jl
- [ ] Improve parallelized function calls
- [ ] Drop GBIF dependency and overloads support?
