### ISSUE TITLE
TODO - Committee document

### ISSUE THREAD

**Issue by gabrieldansereau** [gabrieldansereau/betadiversity-hotspots#5]
## À faire
Pour #3

### Intro
- SDM: 
  - [x] Développer définition & potentiel
- Données
  - [x] Développer sur jeux données
  - [x] Exemple application
- Pertinence
  - [x] Développer sur manque données & pertinence
  - [x] Développer sur scénarios IPCC
- Hypothèse
  - [ ] Ajouter ~ hypothèse sur possibilité prédiction sites exceptionnels
  - [ ] Contraster avec résultats qui montrent surtout extrêmes
  - [x] Mentionner terme hotspots

### Métho
- Collecte données
  - [x] Argument pour Parulines
  - [x] Argument pour Amérique du Nord
  - [x] Développer 1-2 phrases sur WorldClim
  - [x] Opinion Hijmans sur résolution
- Manipulation
  - [x] Transformation ???
  - [x] Citation package Julia
- BIOCLIM
  - [x] Reformuler intro à BIOCLIM
  - [x] Faire réviser pour clarté
- LCBD
  - [x] Rien :tada:
- Validité prédictions
  - [x] Citations pour méthodes
- Méthodes alternatives
  - [x] Point 1: reformuler, brève description méthodes
  - [x] Point 2: reformuler JSDM, retravailler finale
- Changements climatiques & IPCC
  - [x] Raccourcir certaines phrases

### Résultats préliminaires
- [x] **Brouillon à faire rapidement**
  - [x] Formuler en résultats principaux
  - [x] Predictions pour habitats pauvres en espèces
  - [x] Relation LCBD-richesse confirmée
- [x] Retravailler texte
  - [x] Enlever mention effet bordure

### Annexes
- Tableaux
  - [x] WorldClim: mettre à la fin?
  - [x] Variables: tableaux exemple + résumé?
  - [x] Données Canada-ÉU-Mexique?
  - [x] Mise en forme: simple interligne
- Figures
  - [x] Refaire figures sans titre (peut-être en png?)
  - [x] Arranger mise en page avec LaTeX
  - [x] Écrire meilleurs titres
  - [x] sp_raw : mettre NaN en backgroud
  - [ ] sp_sdm : recadrer coordonnées, considérer refaire sans threshold
  - [x] richness : arranger axes
  - [x] lcbd : confusion avec hellinger 
  - [x] relationship: combiner deux séries sur même figure
  - [ ] relationship: faire LCBDrelmoy/richesse
  - [ ] densité: ajouter avec fct dans SimpleSDMLayers

### Autres
- [ ] Préparation liste points dont on souhaite discuter, entre autres
  - Points faibles
  - Points indécis
  - Points non définis
- [x] Mention des analyses avec seuil pour BIOCLIM
- [x] Trouver quoi faire avec la représentation du seuil --> Demander à Tim
- [x] Clarifier si section résultats préliminaires devrait être écrite au passé ou non
- [x] Vraie mise en page double interligne
- [x] Couper au travers :scissors:
- [x] Réviser déclarations audacieuses
- [x] Modifier page titre
- [ ] Se renseigner sur JSDM, MAXENT, trucs du genre avant discussion
