### ISSUE TITLE
TODO - Committee presentation

### ISSUE THREAD

**Issue by gabrieldansereau** [gabrieldansereau/betadiversity-hotspots#6]
## À faire - Présentation comité-conseil

Pour #7

### Introduction & Objectifs

3-4 diapos sur objectifs

- [ ] ~~Plan présentation?~~
- [x] **Première diapo: ajouter sources financement, photos parulines, affiliation?**
- [x] *Slide presentation objectifs/spoilers: grossier figures, réorganiser texte*
- [x] LCBD discontinues
  - [x] Exemples à utiliser: Legendre & De Cacères 2013, Poisot et al. 2017
- [x] **Données disponibles: réarranger, développer un peu**
- [x] Objectifs: réarranger figures, ajouter flèches ou plus, **combiner avec pourquoi méthode intéressante**
- [x] Présentation données eBird & WorldClim: screenshot entrée observation OU enlever et jumeler avec structure données eBird
- [x] Scénarios changements climatiques

### Méthodes & Résultats Préliminaires

10 minutes sur résultats préliminaires

- Figure SDM: 
  - [x] ~~Changer légende single-sp_raw avec Inkscape?~~
  - [x] ~~"Environmental adequability" au lieu de "Probability of occurrence"~~
  - [x] ~~Ramener probabilités à pourcentage relatif? Au moins me préparer à répondre à quelque chose comme ça.~~
  - [x] Répéter « sans seuil »
  - [ ] ~~Titre en haut, un peu détaillé mais pas trop~~
- Figure relation
  - [x] ~~Enlever ombre/contour sur figure relation~~
  - [x] Dédoubler diapos
  - [x] ~~Changer couleur pour vert? Opposé donc plus contrastant~~
  - [x] ~~Tourner légende~~
  - [x] 63 vs 62 espèces?

### Points suite à pratique labo
- [x] Traduire en anglais
- [x] Enlever BIO2 & autres dans tableau
- [x] BIOCLIM: refaire figure classique en retirant modèle HABITAT
- [x] Arranger format tableau (look plus scientifique)
- Fin présentation
  - [x] **Ajouter pistes discussions** (classer comme points à corriger dès maintenant, points à explorer, etc.)
  - [ ] Focus sur démarche exploratoire
  - [ ] Amener discussion sur ce que je veux 
- À investiguer
  - Corrélation population humaine
  - Effet modèle avec absences sur Mexique

### Commentaire pratique perso
- [x] Informative approach
- Richesse: + élevée au Mexique que côte Atlantique malgré manque échantillonages
- Échec identification au centre, pertinence changer échelle & résolution
- Pas trop accent sur types méthodes
- Reminder --> à repositionner?
- Séparer température vs précipitation
- Transition vers richesse spécifique
- LCBD fait ressortir extrêmes, on peut s'y attendre selon théorie, mais pas observée en pratique
- Nombre d'espèces maximum moins élevé au Mexique qu'ailleurs
- Discussion: validité des résultats, déplacer pertinence
- Meth apprentissage machine & influence variables
- Données pour validation
- Scénarios changements climatiques
- Tableau 1 : mentionner que complete checklists

### Autres

- [ ] ~~Échéancier~~
- [x] Références

### À discuter

- Seuil
  - Pas fait dans majorité analyses, pcq: enlève observations extrêmes, mais justement celles qu'on cherche --> Besoin définir intérêt principal étude = choisir si on s'intéresse à extrêmes ou non (prédiction sites centraux devrait rester à peu près la même, mais LCBD devrait changer)
  - À appliquer par variables, pas sur score général
- (Préparation) Biais spatial eBird + biais taxonomique --> je me fie beaucoup à Johnston et al., le relire pour être solide? Trouver autres articles
- Général
  - Difficulté à concilier fait que projet d'analyse/méthodes, mais que analyses préliminaires vraiment pas bien raffinées --> J'imagine qu'il faut que je vois que c'est ça le projet justement?
  - Quelle approche emprunter? Est-ce que je peux poser des questions sur comment on devrait améliorer le projet (donc soulever faiblesses), ou est-ce que seulement une évaluation du projet?
  - Pertinence du point de vue ornithologie

### À arranger par après
- [ ] Duplication codes pour single-species-sdm
  - [ ] Ramener à un seul script (mais problème avec restriction à zone intérêt vs modèle sur ensemble)
  - [ ] Ramener à une seule fonction parallélisée
- [ ] Arranger parallélisation scripts SDM
